### ISSUE TITLE
Capabilities.KubeVersion.GitVersion check can cause headaches

### ISSUE THREAD

**Issue by archonic** [lewagon/rails-k8s-demo#11]
In [ingress.yaml L4](https://github.com/lewagon/rails-k8s-demo/blob/master/charts/rails-k8s-demo/templates/ingress.yaml#L4) there is a kubeversion gitversion check which outputs the apiVersion. I'm sure that's there for a reason but I wanted to share a recent experience regarding it.

I deployed in the morning, everything went well. I ran `gcloud components update`, everything went well. I went to deploy in the afternoon, and I got this error:
```
UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Ingress
```
I downgraded `gcloud components` and nothing changed, still got the error. This was super confusing because all the results were telling me this was a result of updating the `apiVersion` or my helm version and I had done neither. It turns out my kubeversion gitversion had updated over 1.14-0 and I was indeed trying to in-place upgrade a resource with a different apiVersion. This worked in older versions of helm because of a mismatch in the kubectl api - it wasn't supposed to work. They fixed it so now it will correctly error if trying to in-place update a resource's apiVersion.

This repo is just a demo but I thought I'd share that in case it helps anyone else. I don't know what a long-term fix would look like. I commented out the if statement and that worked. I'll delete the ingress and recreate it when I can spare the downtime. Perhaps a HA ingress could be replaced without downtime?

**Comment by progapandist** [comment]
This issue is also currently resolved in `seatrain` branch, keep an eye on the master!
